# Generated by Django 4.2.7 on 2024-01-06 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iban", models.CharField(max_length=34, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImportedLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_iban", models.CharField(blank=True, max_length=34)),
                (
                    "imported_from",
                    models.CharField(
                        choices=[("SWEDBANK", "Swedbank")],
                        default="SWEDBANK",
                        max_length=100,
                    ),
                ),
                ("transaction_code", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField()),
                ("beneficiary", models.CharField(blank=True, max_length=200)),
                ("details", models.CharField(blank=True, max_length=400)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(blank=True, default="EUR", max_length=3)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("D", "Debit"), ("K", "Credit")],
                        max_length=1,
                    ),
                ),
                ("record_id", models.BigIntegerField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("reference_no", models.CharField(blank=True, max_length=100)),
                ("doc_nr", models.CharField(blank=True, max_length=100)),
                ("code_in_payer_is", models.CharField(blank=True, max_length=100)),
                ("client_code", models.CharField(blank=True, max_length=100)),
                ("originator", models.CharField(blank=True, max_length=100)),
                ("beneficiary_party", models.CharField(blank=True, max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledger.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntrySubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("life_and_entertainment", "Life and entertainment"),
                            ("home", "Home"),
                            ("income", "Income"),
                            ("transport", "Transport"),
                            ("food_and_drink", "Food and drink"),
                            ("health_and_education", "Health and education"),
                            ("shopping", "Shopping"),
                            ("pets", "Pets"),
                            ("investments", "Investments"),
                            ("financial_expenses", "Financial expenses"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("beneficiary", models.CharField(max_length=200)),
                ("details", models.CharField(max_length=400)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "type",
                    models.CharField(choices=[("D", "Debit"), ("K", "Credit")], max_length=1),
                ),
                ("record_id", models.BigIntegerField(null=True)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("is_recurring", models.BooleanField(default=False)),
                ("non_standard_category", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ledger.account"),
                ),
                (
                    "cancels_out",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this entry cancels out another entry, select the other entry here.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ledger.ledgerentry",
                    ),
                ),
                (
                    "imported_ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ledger.importedledgerentry",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ledger.ledgerentrysubcategory",
                    ),
                ),
            ],
        ),
    ]
